services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ltodic
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    driver: bridge
    name: ecommerce-net

volumes:
  postgres_data:
